name: Wren for GtkSourceView CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install build-essential debhelper --yes

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
