name: Wren for GtkSourceView CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v0.*", "v1.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt install build-essential debhelper libgtksourceview-3.0-common --yes

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Upload Artifacts
      id: uploadArtifacts
      uses: actions/upload-artifact@v4
      with:
        name: gtksourceview-wren-debian
        path: debian/*.deb
        retention-days: 7
        overwrite: true

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    needs: build
  
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/release.yml
        with:
          workflow_run_id: ${{ github.run_id }}
          artifact_id: ${{ steps.uploadArtifacts.outputs.artifact-id }}
